server:
  port: 8088

spring:
  application:
    name: ts-schedule-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://tinystepscdc.com/auth
  datasource:
    url: jdbc:postgresql://postgres-service:5432/schedules?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false
    hibernate:
      ddl-auto: validate

# Eureka client configuration
eureka:
  instance:
    prefer-ip-address: true
    hostname: ts-schedule-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://ts-service-registry:8761/eureka/

# External microservice integration URLs & config
integration:
  doctor-service:
    base-url: http://ts-doctor-service/api/v1/doctors
    timeout-seconds: 10
    max-retries: 3
    enable-circuit-breaker: true
  address-service:
    base-url: http://ts-address-service/api/v1/addresses
    timeout-seconds: 10
    max-retries: 3
    enable-circuit-breaker: true
  user-service:
    base-url: http://ts-user-service/api/v1/users
    timeout-seconds: 10
    max-retries: 3
    enable-circuit-breaker: true
  timing-service:
    base-url: http://ts-timing-service/api/v1/timings
    timeout-seconds: 10
    max-retries: 3
    enable-circuit-breaker: true
  session-service:
    base-url: http://ts-session-service/api/v1/session-types
    timeout-seconds: 10
    max-retries: 3
    enable-circuit-breaker: true
