server:
  port: 8092

spring:
  application:
    name: ts-schedule-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev.tinystepscdc.com/auth
  datasource:
    url: jdbc:postgresql://postgres-service:5432/schedules?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: false
    out-of-order: true
    locations: classpath:db/migration

# Eureka client configuration
eureka:
  instance:
    prefer-ip-address: true
    hostname: ts-schedule-service
    appname: ${spring.application.name}
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info
    home-page-url-path: /
    secure-health-check-url: false
    non-secure-port: ${server.port}
    non-secure-port-enabled: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://ts-service-registry:8761/eureka/
    registry-fetch-interval-seconds: 30
    eureka-service-url-poll-interval-seconds: 30
    initial-instance-info-replication-interval-seconds: 40
    instance-info-replication-interval-seconds: 30
    eureka-server-connect-timeout-seconds: 5
    eureka-server-read-timeout-seconds: 8

# External microservice integration URLs & config
integration:
  doctor-service:
    base-url: http://ts-doctor-service/api/v1/doctors
    timeout-seconds: 10
    max-retries: 3
    enable-circuit-breaker: true
  address-service:
    base-url: http://ts-address-service/api/v1/addresses
    timeout-seconds: 10
    max-retries: 3
    enable-circuit-breaker: true
  user-service:
    base-url: http://ts-user-service/api/v1/users
    timeout-seconds: 10
    max-retries: 3
    enable-circuit-breaker: true
  timing-service:
    base-url: http://ts-timing-service/api/v1/timings
    timeout-seconds: 10
    max-retries: 3
    enable-circuit-breaker: true
  session-service:
    base-url: http://ts-session-service/api/v1/session-types
    timeout-seconds: 10
    max-retries: 3
    enable-circuit-breaker: true
